using System.Drawing;
using System.Drawing.Imaging;
using System.IO;

namespace BluwolfIcons
{
	/// <summary>
	/// A PNG (Portable Network Graphics) image inside an icon.
	/// </summary>
	public class PngIconImage : IIconImage
	{
		/// <summary>
		/// The original image.
		/// </summary>
		public Bitmap Image { get; set; }

		/// <summary>
		/// Creates a new PNG icon image, with <paramref name="image"/> as its original image.
		/// </summary>
		/// <param name="image">The original image to use in this icon image.</param>
		public PngIconImage(Bitmap image)
		{
			Image = image;
		}

		/// <summary>
		/// Gets the PNG icon image data for this image.
		/// </summary>
		/// <returns>The PNG icon image data for this image.</returns>
		public byte[] GetData()
		{
			// PNG images are represented just like in a normal file, so all we do is save to a MemoryStream and return the generated bytes.
			using (var stream = new MemoryStream())
			{
				Image.Save(stream, ImageFormat.Png);
				return stream.GetBuffer();
			}
		}
	}
}
