using System;
using System.IO;
using System.Windows.Media.Imaging;

namespace BluwolfIcons
{
	/// <summary>
	/// A PNG (Portable Network Graphics) image inside an icon.
	/// </summary>
	public sealed class PngIconImage : IIconImage
	{
		private BitmapSource originalImage;

		/// <summary>
		/// The original image.
		/// </summary>
		/// <exception cref="T:System.ArgumentException">Thrown when an image too big is assigned.</exception>
		public BitmapSource OriginalImage
		{
			get { return originalImage; }
			set
			{
				if (value == null)
					throw new ArgumentNullException(nameof(value));

				if (value.PixelWidth > 256 || value.PixelHeight > 256)
					throw new ArgumentException("Image can't be bigger than 256 x 256.", nameof(value));

				originalImage = value;
			}
		}

		/// <summary>
		/// This image's width.
		/// </summary>
		public int Width => OriginalImage.PixelWidth;

		/// <summary>
		/// This image's height.
		/// </summary>
		public int Height => OriginalImage.PixelHeight;

		/// <summary>
		/// This image's bits per pixel.
		/// </summary>
		public int BitsPerPixel => OriginalImage.Format.BitsPerPixel;

		/// <summary>
		/// Creates a new PNG icon image, with <paramref name="image"/> as its original image.
		/// </summary>
		/// <param name="image">The original image to use in this icon image.</param>
		/// <exception cref="T:System.ArgumentNullException">Thrown when <paramref name="image"/> is <c>null</c>.</exception>
		public PngIconImage(BitmapSource image)
		{
			if (image == null)
				throw new ArgumentNullException(nameof(image));

			OriginalImage = image;
		}

		/// <summary>
		/// Gets the PNG icon image data for this image.
		/// </summary>
		/// <returns>The PNG icon image data for this image.</returns>
		public byte[] GetData()
		{
			// PNG images are represented just like in a normal file, so all we do is save to a MemoryStream and return the generated bytes.
			using (var stream = new MemoryStream())
			{
				var encoder = new PngBitmapEncoder();
				encoder.Frames.Add(BitmapFrame.Create(OriginalImage));
				encoder.Save(stream);

				return stream.GetBuffer();
			}
		}

	}
}
